# WARNING:
#   This is the master repository template file.
# All developers must follow the rules defined in this file.
# Add .current_author.ini to your .gitignore file to prevent
# polluting the repository with personal configuration.
# Replace the ISUSER value below with your account name (email address).
ISUSER=ohmycode-cn(ohcode@163.com)