ENABLE_TERM_COMPATIBLE_MODE="true";
ENABLE_TERM_HIGHLIGHT_MODE="false";
ENABLE_TERM_BOLD_FONT_MODE="false";
LOG_TERM_FORMAT_STYLE="text";
LOG_FILE_FORMAT_STYLE="text";
LOG_TERM_OUTPUT_MODE="console";
LOG_FILE_OUTPUT_MODE="console";
LOG_WRITE_FILE_PATH="/var/log/ruacdb";
LOG_WRITE_FILE_NAME="ruacdb.default.log";
LOG_FILE_SIZE_LIMIT="128MB";
LOG_TERM_LEVEL_FILTER="debug";
LOG_FILE_LEVEL_FILTER="debug";
LOG_MINI_LEVEL_FILTER="debug";