ENABLE_TERM_COMPATIBLE_MODE="true";
ENABLE_TERM_HIGHLIGHT_MODE="false";
ENABLE_TERM_BOLD_FONT_MODE="false";
ENABLE_TERM_LOG_PRINT_MODE="false";
LOG_TERM_FORMAT_STYLE="text";
LOG_FILE_FORMAT_STYLE="text";
LOG_OUTPUT_MODE="console";
LOG_WRITE_PATH="/var/log/ruacdb";
LOG_WRITE_FILE="ruacdb.default.log";
LOG_FILE_SIZE_LIMIT="128MB";
TERM_LOG_LEVEL_FILTER="debug";
FILE_LOG_LEVEL_FILTER="debug";
MINIMUM_LOG_LEVEL="debug";